metadata_paths:
  - "/global/cscratch1/sd/helenqu/plasticc_test_data/metadata_0.csv"
  - "/global/cscratch1/sd/helenqu/plasticc_test_data/metadata_1.csv"
lcdata_paths:
  - "/global/cscratch1/sd/helenqu/plasticc_test_data/lcdata_0.csv"
  - "/global/cscratch1/sd/helenqu/plasticc_test_data/lcdata_1.csv"
ids_path: "/global/cscratch1/sd/helenqu/plasticc_test_heatmaps/no_ttfd_snr_5/32_x_90_heatmaps/peak-50+130_cuts_from_full_ids.hdf5"
output_path: "/global/cscratch1/sd/helenqu/plasticc_test_heatmaps/no_ttfd_snr_5/32_x_180_peakrange_cuts"

wavelength_interval: 221.875
mjd_interval: 1.0

Ia_fraction: 0.5 # "categorical" for class-balanced categorical split
categorical_min_per_type: 200
categorical_max_per_type: 2000

# save intermediate results as json file if apply_cuts is time-intensive
save_to_json: True
# if data_cuts dies in the class balancing phase, skip the apply_cuts if save_to_json was true last run
from_json: False

sn_type_id_to_name:
  42: "SNII"
  52: "SNIax"
  62: "SNIbc"
  67: "SNIa-91bg"
  64: "KN"
  90: "SNIa"
  95: "SLSN-1"
