metadata_paths:
  - "/project2/rkessler/SURVEYS/DES/USERS/helenqu/PIP_HELEN_PLASTICC_NON-IA86f49_NONIaMODEL4-0010_HEAD.csv"
lcdata_paths:
  - "/project2/rkessler/SURVEYS/DES/USERS/helenqu/PIP_HELEN_PLASTICC_NON-IA86f49_NONIaMODEL4-0010_PHOT.csv"
input_path: #alternatively, pass in a dir path and look for PHOT and HEAD files in dir
heatmaps_path: "/project2/rkessler/SURVEYS/DES/USERS/helenqu/test_create_heatmaps"
# omitted ids_path

num_wavelength_bins: 32
num_mjd_bins: 180

Ia_fraction: 0.5 # "categorical" for class-balanced categorical split
categorical_min_per_type: 200
categorical_max_per_type: 2000

# save intermediate results as json file if apply_cuts is time-intensive
save_to_json: True
# if data_cuts dies in the class balancing phase, skip the apply_cuts if save_to_json was true last run
from_json: False

sn_type_id_to_name:
  42: "SNII"
  52: "SNIax"
  62: "SNIbc"
  67: "SNIa-91bg"
  64: "KN"
  90: "SNIa"
  95: "SLSN-1"
