# metadata_paths:
  # - "/global/cscratch1/sd/helenqu/plasticc_test_data/metadata_0.csv"
  # - "/global/cscratch1/sd/helenqu/plasticc_test_data/metadata_1.csv"
# lcdata_paths:
  # - "/global/cscratch1/sd/helenqu/plasticc_test_data/lcdata_0.csv"
  # - "/global/cscratch1/sd/helenqu/plasticc_test_data/lcdata_1.csv"
input_path: "/global/cscratch1/sd/helenqu/plasticc_sdss_filters_csv"
ids_path: "/global/cscratch1/sd/helenqu/plasticc_sdss_filters_heatmaps/0_5_Ia_split_heatmaps_ids.hdf5"
heatmaps_path: "/global/cscratch1/sd/helenqu/plasticc_sdss_filters_heatmaps"

num_wavelength_bins: 32
num_mjd_bins: 180
wavelength_interval: 221.875
mjd_interval: 1.0

Ia_fraction: 0.5 # "categorical" for class-balanced categorical split
categorical_min_per_type: 200
categorical_max_per_type: 2000

# save intermediate results as json file if apply_cuts is time-intensive
save_to_json: True
# if data_cuts dies in the class balancing phase, skip the apply_cuts if save_to_json was true last run
from_json: False
categorical: False

sn_type_id_to_name:
  42: "SNII"
  52: "SNIax"
  62: "SNIbc"
  67: "SNIa-91bg"
  64: "KN"
  90: "SNIa"
  95: "SLSN-1"
