metadata_paths:
  - "/global/cscratch1/sd/helenqu/plasticc_test_data/metadata_0.csv"
  - "/global/cscratch1/sd/helenqu/plasticc_test_data/metadata_1.csv"
lcdata_paths:
  - "/global/cscratch1/sd/helenqu/plasticc_test_data/lcdata_0.csv"
  - "/global/cscratch1/sd/helenqu/plasticc_test_data/lcdata_1.csv"
ids_path: "/global/cscratch1/sd/helenqu/plasticc_test_heatmaps/no_ttfd_snr_5/32_x_90_heatmaps/peak-50+130_cuts_from_full_ids.hdf5"
output_path: "/global/cscratch1/sd/helenqu/plasticc_test_heatmaps/peak-50+130_cuts"

wavelength_interval: 
  - 221.875
  - 443.75
  - 887.5
  - 1775 
mjd_interval: 
  - 1.0
  - 2.0
  - 6.0
  - 18.0

Ia_fraction: 0.5

sn_type_id_to_name:
  42: "SNII"
  52: "SNIax"
  62: "SNIbc"
  67: "SNIa-91bg"
  64: "KN"
  90: "SNIa"
  95: "SLSN-1"
